name: Bazel

on:
  pull_request: {}
  push: {}

jobs:
  build_and_test_ubuntu20:
    name: Linux Ubuntu 22.04 build <GCC 9.3.0>
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Build
        run: |
          cd tests
          bazelisk build --config=gcc11 //...
